# vim: set ft=ansible:
---

######################### Prep hosts to run OpenShift Installer

- name: Step 004.1 - Host preparation for OpenShift 4 deployment
  hosts: bastions
  become: true
  gather_facts: False
  tags:
    - step004
    - step004.1
  tasks:
  - name: Run OCP4 Host Provisioner
    include_role:
      name: host-ocp4-provisioner

######################### Run OpenShift Installer

# - name: Step 004 LE certs
#   hosts: bastions
#   gather_facts: false
#   become: true
#   vars:
#     _certbot_dns_provider: "rfc2136"
#     _certbot_domain: "api.{{ guid }}.{{ osp_cluster_dns_zone }}"
#     _certbot_wildcard_domain: "*.apps.{{ guid }}.{{ osp_cluster_dns_zone }}"
#     _certbot_remote_dir: "/home/{{ ansible_user }}"
#     _certbot_remote_dir_owner: "{{ ansible_user }}"
#     _certbot_install_dir: "/home/{{ ansible_user }}/certificates"
#     _certbot_install_dir_owner: "{{ ansible_user }}"
#     _certbot_production: False
#     _certbot_user: "{{ ansible_user }}"
#     _certbot_cache_archive_file: "{{ output_dir|d('/tmp') }}/{{ guid }}-certs.tar.gz"
#     _certbot_use_cache: False
#     use_python3: "{{ all_use_python3 | d(True) }}"
#   tasks:
#     - name: Copy credentials to host temporarily
#       template:
#         src: ./files/rfc2136.ini.j2
#         dest: /home/{{ _certbot_user }}/.rfc2136.ini
#         owner: "{{ _certbot_user }}"

#     - import_role:
#         name: host-lets-encrypt-certs-certbot

#     - name: Remove credentials once LE certs complete
#       file:
#         state: absent
#         path: /home/{{ _certbot_user }}/.rfc2136.ini
#       when: _certbot_setup_complete

#     - name: Copy the LE root certs into trusted bundle
#       copy:
#         dest: /etc/pki/ca-trust/source/anchors/le-chain.pem
#         src: /home/{{ ansible_user }}/certificates/chain.pem
#         remote_src: true
    
#     - name: Update CA trust
#       command: update-ca-trust

- name: Step 004.2 Install OpenShift
  hosts: bastions
  gather_facts: false
  become: false
  tags:
    - step004
    - step004.2
  tasks:
  - name: Call Role to install OpenShift
    when: install_ocp4 | d(True) | bool
    include_role:
      name: host-ocp4-installer
