apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp
    challenge: true
    login: true
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "{{ idm_bind_dn }}"
      bindPassword:
        name: opentlc-ldap-secret
      insecure: false
      ca:
        name: opentlc-ldap-ca-cert
      url: "{{ idm_url }}"