---

- name: "Create mig-operator and MigrationController"
  when: not migration_workload_destroy|bool
  block:
  - name: "Create mig-operator"
    k8s:
      state: present
      definition: "{{ lookup('template', 'operator.yml.j2' ) }}"

  - name: "Create MigrationController resource"
    k8s:
      state: present
      definition: "{{ lookup('template', 'controller-3.yml' ) }}"

- name: "Remove mig-operator and MigrationController"
  when: migration_workload_destroy|bool
  block:
  - name: "Remove mig-operator"
    k8s:
      state: absent
      definition: "{{ lookup('template', 'operator.yml.j2' ) }}"

  - name: "Remove MigrationController resource"
    k8s:
      state: absent
      definition: "{{ lookup('template', 'controller-3.yml' ) }}"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
