---

- name: "Deploy downstream mig operator using OLM"
  when: not migration_workload_destroy|bool
  block:
    - name: "Create {{ mig_migration_namespace }} namespace"
      k8s:
        name: "{{ mig_migration_namespace }}"
        kind: Namespace
        state: present

    - name: "Create OperatorGroup"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-operatorgroup.yml.j2' ) }}"

    - name: "Create operator subscription"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-subscription-downstream.yml.j2' ) }}"


- name: "Remove downstream mig operator using OLM"
  when: migration_workload_destroy|bool
  block:
    - name: "Remove operator subscription"
      k8s:
        state: absent
        definition: "{{ lookup('template', 'mig-operator-subscription-downstream.yml.j2' ) }}"

    - name: "Remove OperatorGroup"
      k8s:
        state: absent
        definition: "{{ lookup('template', 'mig-operator-operatorgroup.yml.j2' ) }}"

    - name: "Remove {{ mig_migration_namespace }} namespace"
      k8s:
        name: "{{ mig_migration_namespace }}"
        kind: Namespace
        state: absent

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
