---
become_override: False
ocp_username: "system:admin"
silent: False

admin_user: opentlc-mgr
idm_url: ldaps://ipa1.opentlc.com:636/cn=users,cn=accounts,dc=opentlc,dc=com?uid
idm_ca_url: http://ipa.opentlc.com/ipa/config/ca.crt
idm_bind_dn: "uid=ose-mwl-auth,cn=users,cn=accounts,dc=opentlc,dc=com"
